[log]
mode = "off"
timing = false

[log.stdout]
level = "warn"

[log.file]
level = "info"
# path = "~/.cache/runcore/runcli.log"

[[persistence]]
type = "sqlite"
enabled = true
# database = "~/.local/share/runcore/jobs.db"
max_records = -1
max_age = "" #ISO 8601 duration format

[plugins]
enabled = false
# load = ["taro_sns"]
